language: objective-c
osx_image: xcode10.1
cache:
- bundler
- cocoapods

install:
- bundle install

stages:
- name: test
  if: type = push AND branch != beta-release AND branch != prod-release
- name: beta
  if: type = push AND branch = beta-release
- name: prod
  if: type = push AND branch = prod-release

jobs:
  include:
  - stage: prod
    script:
    - fastlane prod
    before_script:
    - "./scripts/add-key.sh"
    - "./scripts/prepare-git.sh"
    after_script:
    - "./scripts/remove-key.sh"

  - stage: beta
    script:
    - fastlane beta
    before_script:
    - "./scripts/add-key.sh"
    - "./scripts/prepare-git.sh"
    after_script:
    - "./scripts/remove-key.sh"

  - stage: test
    xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XS
    script:
    - fastlane test

env:
  global:
  - PROFILE_NAME: TryTravisCI
  - XCODE_PROJECT: Try-TravisCI.xcodeproj
  - GIT_URL: BeerPoldet/Try-TravisCI
  - CHANGE_LOG_URL: https://github.com/BeerPoldet/Try-TravisCI/releases/tag
  - secure: VE6zcNkr1e60W/kd/lxu4iBv3vOEzAw5bfbLDtgcTIhrwJORAVnAWJRkT/0J0P+9hZgcDmqVQhB93TyOr9p+lOJNDz8EsfSJrJEL5VsFXkRv/LzRcYyYL6E0x1brxu1ATjNhXyC3E2mqz88W2BDzL9ob3jnJ1HlwuXHkByN3VveyGNmimxdKNuzYeOJqbmb3GcUCcRjAaSnwoUYuILe0wSiDg7bhGQkumZs2hZr9y08+slNg7IOJJN7CW0pTxQwFBjtIPEDn6wosqXSvHAJhmXRQ2OK2Wrt/HspT6AQE3dw71NZeoDjAIdvPmHQlbyP48ABji7y4lXeRZrrLNpDiUZILZ1uNnlDjSqBO9An8cEQnP2Db7sx4AYYHN+vk8lVm7omjvjngoE5Y3uw/o1PhHCENW8AMXWWE4/aAMVFS779uXUCrNXHVq6pTrubPie5tFY5UZBbehu7+zDR/m9grLWA/4Wkcrt0xEZo0KXNHrljiVRrsuf7DhSaJT+zVRPWci+U7r0isHNaThPVLA2g8hEIMq18qpwN0vCJVn6HE++RcKHhsYNLxIyt5ENjIbEMFlV7AaX+1JO121TsaxkdKsLFSd6OROhdN2WKH6MkcCIPanfTP9fpeEbItjjOZliDZqIcgsRUwA9Ic4w74ltgsN9QiIxlq9lvufEzD+rTpeTo=
  - secure: izqdo6a1jJynoulAJaNVBmyscDK3xcqXU38POhtheYWJseqvi4+XM1pgeHnAyF8l3zJrRmRDWYeTdWufWBEJyEZct79GnsZSEu84FFyMvXxzsmC0xlm38OEsqEwBvxg9FaYlqawICL1WXe8IW2V3cGMYMDprfpho/uwwJxwFzJ3RPKobHTZsTO2IY6821/dsuEhtoxkSna9TqzzMBtpdrC5/OlEUmFH/qao0qThkjCnSut1VWDYwkLc/J9VHAXmGF95IxtxUSjYkiySVDQ3G2WN6qM27ThZoAWiujsvpdSagnU359RzgaxXJMzSf6xQc6/m6dmgefC2Nru6X/QReCRInlnytcPVrqJl4mHCvwrz443WG2g4OcQqEgMl9zV+HhAshuxpu1YbrI5xYlbTxqOpbKL7c1yCc27D/e8P94VwATsIvXxyaTYhtD8QDYA0npsf5T4wX05BLQUbaw5QBtCgTjWId+Jbu0mTtPEfr1dbDYF4q8nTJTihgUmMqrlI9gN+/IcmU92PTIhq+luwIU+60xRm5V+yzT/0QqfuOKQwZgjRNaNjoMXMEPdOWatdhf2U7rYptCoDg4qPbXoSEEAOzEokYcUequBZBINfxQ1d4YNX1ZrDPY1EG1hBpc8Eu0ahqfN4WRZC0akdywI6guf/3ZYF+A76MbSi5cWwacdk=
  - secure: avGZzj+bM9CFwUeHsu/IQPYxQBzqdcWLC+tKwc1Svst0G+Heg75A5CnPINQiLyPDWRmF03tTNtmv3l0xpZsmVM67uhxiJky71aSrGiMzk5wFkc0BzZdCaq0xBuPRfwssddOEs95HmbnD+5PxwVTd6z1HzR4Nq+zGK2UpK6euN8c/Hs5W5XEbmzn7N87mphqQg4CIA1zXFtCggc1z/yaXXILuym9zCh3d7v+2QgWmQYKA2wjPS9cCLpyyeAAROhbVTJkBv33CgTquC2LfAx55Z9qXXiQW0LKxvB93IapN/E/CyMoeJLkmmiC9jB4PF5HaGumCSfXZOeJdaMTovple420MfHHGteAc6FdNXD37CJsShdutVkG66HTsWwMIz65FWVYhD+ThN+Lf5ZSIhcfMlhIzimaFYeEyf1knmLyRENkG0ryFrMlqzdnmB/hV6O4THsUJ4M2XoMnX0Sc6DToZCED8/TBTNjZAi/AnePF7vrt3GvNh+P3xmD6Yl0XAtlbVppTU/WjrlhGJ3IMZacCHNHzWkb2NK0cgDKEe8TUp/Y+uGHSw8XOSK3f9wHmdSyrr/LWkb3Olhfu9WkSIWjEQzKZIjs1jEGuLZn5UQMAI6K0Lzk59/NxQeaqWASKdVGkToCb1WNHbrK1ASOpvtW2INwT7I4d9//CX1bz0xhslQiU=
  - secure: cJSoGzz0lRRfdTf+JiKI7rMUjCEaXqe7D0FLGdz7JeJX5M2FOnM3cR6RlVM47g3JQ4dpuRNXtHlXjKw0AFCCi5wHaek6JMgdERf4sbxYqphVtBGqp+bZOVxWLFvUHGBf5CD3HYL/HRRx6j2OAYAlX/v4UvzigdB85/NZrV7Nozi+257yBb2d4ICuMOEWh4XuLiNRRpZln8/vAcKtIWUM2m4wHY/8wAas1iBnTucVTzJsoPg9uOn7KkquA6mtu0hy0s8iryytdtJghTX9aSQYSrTy/1CrwvAIZgE7rGFq8IcnzNWY7UqfL7IBIJI25cPm8fveVp3g4wEVkkYKigUgfsKvkdVnHwfFcfqfyf8s0hpt6c67s85Fro7gt66tfQpK4jEMR3tpbY0ktASqFB2hwYNhrG9YK7krORd1fJ0L0uBlHdGfMsLxzrvFF1Qs9Eu4YPuzhvjwxn7uw6fUtX765lMeKCl7ugLSokZ5KZa3lXFt+nrdC0ag9Wzxzcb+exHLVNfofiLknydaoQBbn+z+W8Zrc+U0q1qjDcaS/4tM8/6K43pOjIqQeld+7lWfn8tNV1ykHmKa9d+FyJ5NdN82hDDX4NIJiww/ChrC47jE/gKvRsxj5OJJhvPeAsNZ4Lp3hAAciMiEDMxRwP5Gy0US2p2zRJRmxYsNAPp8ZI4T2U8=
  - secure: qXJFnhCicImy+mw2WI1INEQl6gYaphzOy9JQIupaB13cdTTtVv2EwfO65+quzI/3Vc6pSWI0TLgRStClONEVf1grkWC80RjgTfM6UnT0lXvwvV6HrAaguXfzp/nv++3YTSrZo9iJAmTFufsRaxhRS0zqbM75Q92X0ix0yt7I5UP2p3n50YNrkP1phQNntnWg8IMQFWyHxUUqaXVIzp9fPlxtlNuhiXY7tj///hJUXjGm00O3l5r9IyGQotQUvJzucMjgf+KPPXhEs0GMN4l+Y/8GNosiOPOlWNVp1lqTxwjpQ3fhLh/pOc0Cq7bDCIapVHCM2isgNDRjpw3uwoaKs18YtPNVT/gRdmeqmGdpPqB1aujNotP+QgA+usk7LmVnOK9yv/5uDwdMRMeExg/Ji3s/RyUOKWAIU3UAROJTbqSMkWp9tHlBTj6VAf+GGA6e2UMwurGk7+MVOhWDL3COzDT7QOLVVDe9FmKhAbM/OE61bGOhot6b64GJc/SStg796gXE5T04+ZtWLEZm9wTLgNCaBe8x4ZavcpPp6yu+yUTMZ1eSlCZ687P8RWtMoprEH15i5qwYiae6xy2X/DhVm8ediukK3fHTbzUY7o/owWnmKSg8hOujKPwQrvkuYY0n6UZHC5yQ+uGebMTCwBZ/rBfsNjhGpKyfIpaJZItlqAc=
