# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

def next_build_number(xcodeproj)
  build_number = [
    get_build_number(xcodeproj: xcodeproj).to_i, 
    latest_testflight_build_number
  ].max + 1
end

def commit_and_push(xcodeproj, build_number, tag)
  commit_version_bump(
    xcodeproj: xcodeproj,
    message: format("[SKIP CI] New Build: %d 🎁", build_number),
    force: true
  )
  add_git_tag(tag: tag)
  branch_name = git_branch
  print_message "Pushing to remote_branch: #{branch_name}"
  push_to_git_remote(
    local_branch: "HEAD",
    remote_branch: branch_name
  )
end

def create_change_log(tag)
  changelog_url = ENV["CHANGE_LOG_URL"]
  "QA Testing Release\nYou can view change logs: #{changelog_url}/#{tag}"
end

def print_message(message)
  puts "\n"
  puts "################################################"
  puts "# #{message}"
  puts "################################################"
  puts "\n"
end

configs = {
  debug => {
    scheme => "Try-TravisCI-Debug",
    create_tag => -> (build_number, build_type) { "v#{build_number}-#{build_type}" }
  },
  beta => {
    scheme => "Try-TravisCI-Beta",
    create_tag => -> (build_number, build_type) { "v#{build_number}-#{build_type}" }
  },
  prod => {
    scheme => "Try-TravisCI-Release",
    create_tag => -> (build_number) { "v#{build_number}" }
  }
}

xcodeproj = ENV["XCODE_PROJECT"]

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    print_message("Stage beta")
    config = configs.beta
    
    build_number = next_build_number(xcodeproj)
    tag = config.create_tag.call(build_number, build_type)
    changelog = create_change_log(tag)
    print_message("Change Logs: #{changelog}")
    
    ensure_git_status_clean
    increment_build_number(
      build_number: build_number,
      xcodeproj: xcodeproj
    )
    build_app(
      project: xcodeproj,
      scheme: config.scheme
    )
    upload_to_testflight(
      changelog: changelog,
      skip_waiting_for_build_processing: false,
      reject_build_waiting_for_review: true
    )
    commit_and_push(xcodeproj, build_number, tag)
      # upload_to_app_store(
    #   force: true,
    #   skip_metadata: true,
    #   skip_screenshots: true,
    #   skip_app_version_update: true,
    #   submit_for_review: false,
    #   keywords: {
    #     'default' => 'keyword-qa',
    #     'th-TH' => 'keyword-qa-th'
    #   },
    #   promotional_text: {
    #     'default' => 'promotional_text-qa',
    #     'th-TH' => 'promotional_text-qa-th'
    #   },
    #   release_notes: {
    #     'default' => "Shiny and new",
    #     'th-TH' => "ทดสอบ"
    #   }
    # )
  end

  lane :test do
    print_message("Stage test")
    run_tests(scheme: scheme)
  end
end