# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

xcodeproj = ENV["XCODE_PROJECT"]
scheme = ENV["XCODE_SCHEME"]

default_platform(:ios)

def do_increment_build_number(xcodeproj)
  build_number = [
    get_build_number(xcodeproj: xcodeproj).to_i, 
    latest_testflight_build_number
  ].max + 1
  increment_build_number(
    build_number: build_number,
    xcodeproj: xcodeproj
  )
end

def commit_and_push(xcodeproj)
  commit_version_bump(
    xcodeproj: xcodeproj,
    message: format("[SKIP CI] New Build: %d 🎁", build_number),
    force: true
  )
  add_git_tag
  push_to_git_remote
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    do_increment_build_number(xcodeproj)
    commit_and_push(xcodeproj)
    build_app(
      project: xcodeproj,
      scheme: scheme, 
      codesigning_identity: ENV["DEVELOPER_NAME"],
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          ENV["BUNDLE_ID"] => ENV["PROFILE_NAME"]
        }
      }
    )
    changelog_from_git_commits
    upload_to_testflight
  end

  lane :test do
    run_tests(scheme: scheme)
  end
end